### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by c00ler123** [stanislavkovin/fssp-request#1]
Добрый день, видимо изменили api.
Не делали еще revers ? 
Ваш метод не работает 
https://api.fssprus.ru/api/search? ресурс уходит в error 500 либо в пустой ответ

**Comment by stanislavkovin** [comment]
Пофиксил. Теперь работает.

**Comment by c00ler123** [comment]
Спасибо тебе огромное )

**Comment by c00ler123** [comment]
p.s. добавь код региона 0 (Все регионы) либо 0пробел
